var max_nodes = 100;
var rsm_nodes = {};
var gen_nodes = {};

var calculate = function(fd, fr) {
	var common_nodes = [];

	for(var i = 0; i < fd.length; i++) {
		for(var j = 0; j < fr.length; j++) {
			if(parseInt(fd[i]) == parseInt(fr[j])) {
				common_nodes.push(fd[i]);
			}
		}
	}

	precision = common_nodes.length/fd.length;
	recall = common_nodes.length/fr.length;

	F = 2*((precision*recall)/(precision+recall));

	return result = {
		"precision": precision,
		"recall": recall,
		"F": F
	};
};

var getSimilarArray = function(gen_nodes, rsm_nodes, target_node) {
	var len_gen_nodes = gen_nodes.length;
	var len_rsm_nodes = null;
	var similar_index = 0;
	var similar_array = [];

	// This loop is generating the array containing all the similarity index.
	for(var nodes in rsm_nodes) {
		var target_node_found = false;

		// skip those nodesets array where the target node is not present in the nodesets generated by RSM algorithm.
		for(var i = 0; i < rsm_nodes[nodes].length; i++) {
			if(target_node == parseInt(rsm_nodes[nodes][i])) {
				target_node_found = true;
			}
		}

		if(rsm_nodes.hasOwnProperty(nodes) && target_node_found) {
			len_rsm_nodes = rsm_nodes[nodes].length;
			if(len_gen_nodes > len_rsm_nodes) {

				for(var i = 0; i < gen_nodes.length; i++) {
					for(var j = 0; j < rsm_nodes[nodes].length; j++) {
						if(parseInt(gen_nodes[i]) == parseInt(rsm_nodes[nodes][j])) {
							similar_index++;
						}
					}
				}
				similar_array.push(similar_index/len_gen_nodes)

			} else {

				for(var i = 0; i < rsm_nodes[nodes].length; i++) {
					for(var j = 0; j < gen_nodes.length; j++) {
						if(parseInt(gen_nodes[j]) == parseInt(rsm_nodes[nodes][i])) {
							similar_index++;
						}
					}
				}
				similar_array.push(similar_index/len_rsm_nodes)
			}
		}
		similar_index = 0;
	}

	var comparison_index = similar_array[0];
	var final_index = 0;
	var similar_index_array = [];

	var similar_index_object = {};

	// Loop to generate the similar index object with index as key and the array of similar nodesets array as the value.
	for(var i = 0; i < similar_array.length; i++) {
		if(similar_index_object.hasOwnProperty(similar_array[i])) {
			similar_index_object[similar_array[i]].push(i+1);
		} else {
			similar_index_object[similar_array[i]] = [i+1];
		}
	}

	console.log(similar_index_object);

	// loop over similarity index object and find the greatest index.
	for(var index in similar_index_object) {
		if(parseFloat(comparison_index) < parseFloat(index)) {
			comparison_index = parseFloat(index);
		}
	}

	var shortest_length = 0;

	// This loop is fetching the best nodeset from the equal similar index nodesets array.
	for(var i = 0; i < similar_index_object[comparison_index].length; i++) {
		if((shortest_length < rsm_nodes[similar_index_object[comparison_index][i]].length) && (len_gen_nodes <= rsm_nodes[similar_index_object[comparison_index][i]].length)) {
			shortest_length = similar_index_object[comparison_index][i];
		}
	}
	console.log(similar_array);
	console.log(rsm_nodes);
	return rsm_nodes[shortest_length];

};

// fetch nodesets data for RSM algorithm
$.get("../../communities.txt", function(data) {

	data = data.split("#");
	for(var i = 0; i < data.length; i++) {
		if(data[i] != "\n") {
			rsm_nodes[i+1] = data[i].trim().split("\n");
		}
	}

	// Fetch nodesets for any other algorithm.
	$.get("../directed_networks/community.dat", function(data) {
		data = data.split("\n");
		var arr = [];
		for(var i = 0; i < data.length; i++) {
			data[i] = data[i].trim();
			if(gen_nodes.hasOwnProperty(data[i])) {
				gen_nodes[data[i]].push(i+1);
			} else {
				gen_nodes[data[i]] = [i+1];
			}
		}

		// Select the node for which yoou have to run the calculations.
		var fd = getSimilarArray(gen_nodes['2'], rsm_nodes, 2);
		var fr = gen_nodes['2'];

		console.log(fd);	
		console.log(fr);
		console.log(calculate(fd, fr));


	});

});

var precisionArray = [1, 0.8, 0.5, 0.5, 0.444, 0.33, 0.1];
var recallArray = [1, 1, 0.750, 0.60, 0.55, 0.5, 0.1];
var fscoreArray = [1, 0.888, 0.6, 0.545, 0.46, 0.397, 0.1];
//var nmiArray = [0.1724, 0.0944, 0.0800, 0.0870, 0.0669, 0.0866, 0.0838];
var nmiArray = [0.56, 0.52, 0.5, 0.48, 0.4, 0.42, 0.43];
var omegaArray = [ 0.6, 0.55, 0.54, 0.51, 0.46, 0.4, 0.39]
var overlappingmodularityArray = [ 0.62, 0.678, 0.08]



// Precision data
var precisionCopra = [0.16, 0.16, 0.16, 0.14, 0.14, 0.12, 0.12];
var precisionCis = [0.1, 0.05, 0.04, 0.03, 0.02, 0.01, 0.01];
var precisionCfinder = [0.4, 0.38, 0.36, 0.35, 0.32, 0.30, 0.28];
var precisionLink = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1];
var precisionGce = [0.682, 0.184, 0.02, 0.03, 0.05, 0.08, 0.1];

// Recall data
var recallCopra = [0.97, 0.97, 0.93, 0.82, 0.70, 0.68, 0.63];
var recallCis = [0.61, 0.18, 0.10, 0.10, 0.08, 0.10, 0.02];
var recallCfinder = [0.38, 0.35, 0.32, 0.30, 0.26, 0.25, 0.22];
var recallLink = [0.99, 1, 1, 1, 1, 1, 1];
var recallGce = [0.25, 0.02, 0, 0, 0, 0, 0];

// fscore data
var fscoreCopra = [0.28, 0.29, 0.29, 0.25, 0.23, 0.22, 0.22];
var fscoreCis = [0.2, 0.05, 0.04, 0.03, 0.03, 0.04, 0.02];
var fscoreCfinder = [0.38, 0.37, 0.35, 0.30, 0.28, 0.25, 0.22];
var fscoreLink = [0.19, 0.19, 0.19, 0.19, 0.19, 0.19, 0.19];
var fscoreGce = [0.37, 0.03, 0.01, 0.01, 0.02, 0.04, 0.05];


// nmi data
var nmiCopra = [0.55, 0.54, 0.51, 0.48, 0.45, 0.35, 0.33]
var nmiCis = [0.62, 0.52, 0.51, 0.5, 0.5, 0.48, 0.54]
var nmiCfinder = [0.5, 0.45, 0.47, 0.45, 0.43, 0.42, 0.41]
var nmiLink = [0.24, 0.23, 0.23, 0.22, 0.22, 0.218, 0.21]
var nmiGce = [0.88, 0.78, 0.77, 0.75, 0.72, 0.7, 0.66]

// omega data
var omegaCopra = [0.88, 0.72, 0.66, 0.62, 0.55, 0.52, 0.5]
var omegaCis = [0.65, 0.59, 0.55, 0.5, 0.48, 0.45, 0.43]
var omegaCfinder = [0.55, 0.48, 0.42, 0.38, 0.35, 0.37, 0.37]
var omegaLink = [0.4, 0.38, 0.38, 0.36, 0.35, 0.35, 0.35]
var omegaGce = [0.88, 0.68, 0.6, 0.55, 0.52, 0.5, 0.47]

// overlappingmodularity data
var overlappingmodularityCopra = [0.55, 0.68, 0.08]
var overlappingmodularityCis = [0.71, 0.15, 0.09]

var overlappingmodularityLink = [0.4, 0.45, 0.01]
var overlappingmodularityGce = [0.58, 0.67, 0.15]

var data = {
	precision: {
		rsm: precisionArray,
		copra: precisionCopra,
		cis: precisionCis,
		cfinder: precisionCfinder,
		link: precisionLink,
		gce: precisionGce
	},
	recall: {
		rsm: recallArray,
		copra: recallCopra,
		cis: recallCis,
		cfinder: recallCfinder,
		link: recallLink,
		gce: recallGce
	},
	fscore: {
		rsm: fscoreArray,
		copra: fscoreCopra,
		cis: fscoreCis,
		cfinder: fscoreCfinder,
		link: fscoreLink,
		gce: fscoreGce
	},

    nmi: {
        rsm: nmiArray,
        copra: nmiCopra,
        cis: nmiCis,
        cfinder: nmiCfinder,
        link: nmiLink,
        gce: nmiGce
    },

    omega: {
        rsm: omegaArray,
        copra: omegaCopra,
        cis: omegaCis,
        cfinder: omegaCfinder,
        link: omegaLink,
        gce: omegaGce
    },
    
    overlappingmodularity: {
        rsm: overlappingmodularityArray,
        copra: overlappingmodularityCopra,
        cis: overlappingmodularityCis,
       
        link: overlappingmodularityLink,
        gce: overlappingmodularityGce
    },

};

var plot = function(data, graph) {

	var name = null;

	switch (graph){
		case '#precision':
			data = data.precision;
			name = 'Precision';
			break;

		case '#recall':
			data = data.recall;
			name = 'Recall';
			break;

		case '#fscore':
			data = data.fscore;
			name = 'F-score';
			break;
        case '#omega':
            data = data.omega;
            name = 'Omega';
            break;
        case '#nmi':
            data = data.nmi;
            name = 'NMI';
            break;
        case '#overlappingmodularity':
            data = data.overlappingmodularity;
            name = 'overlappingmodularity';
            break;
	}


	$('body').find(graph).highcharts({
            chart: {
                zoomType: 'x'
            },
            title: {
                text: name+' vs. Om'
            },
            xAxis: {
            	minTickInterval: 1,
                type: 'linear',
                title: {
                    text: 'Om',
                    legend: false
                }
            },
            yAxis: [{
                title: {
                    text: name,
                    legend: false
                },
                minTickInterval: 0.1,
                max: 1,
                min: 0,
                minRange: 1,
                lineWidth: 1
            },
            {
            	title: {
                    text: '',
                },
                opposite: true,
                
                lineWidth: 1
            }],
            legend: {
                enabled: true,
                layout: "vertical"
            },
            credits: {
                enabled: false
            },
            tooltip: {
                valueSuffix: '',
                crosshairs: true,
                shared: true,
                useHTML: true,
                enabled: true
            },
            series: [{
                type: "line",
                name: "RSM",
                color: "#FF0000",
                pointInterval: 1,
                pointStart: 2,
                data: data.rsm,
                lineWidth: 1
            },
            {
                type: "line",
                name: "COPRA",
                color: "green",
                pointInterval: 1,
                pointStart: 2,
                data: data.copra,
                lineWidth: 1
            },
            {
                type: "line",
                name: "CIS",
                color: "blue",
                pointInterval: 1,
                pointStart: 2,
                data: data.cis,
                lineWidth: 1
            },
            {
                type: "line",
                name: "CFinder",
                color: "black",
                pointInterval: 1,
                pointStart: 2,
                data: data.cfinder,
                lineWidth: 1
            },
            {
                type: "line",
                name: "Link",
                color: "orange",
                pointInterval: 1,
                pointStart: 2,
                data: data.link,
                lineWidth: 1
            },
            {
                type: "line",
                name: "GCE",
                color: "#AC0D96",
                pointInterval: 1,
                pointStart: 2,
                data: data.gce,
                lineWidth: 1
            }]
        });
};

$('body').find('#nmi').highcharts({
            chart: {
                zoomType: 'x'
            },
            title: {
                text: 'NMI'
            },
            xAxis: {
            	minTickInterval: 1,
                type: 'linear',
                title: {
                    text: 'Om',
                    legend: false
                }
            },
            yAxis: [{
                title: {
                    text: 'NMI',
                    legend: false
                },
                minTickInterval: 0.1,
                max: 1,
                min: 0,
                minRange: 1,
                lineWidth: 1
            },
            {
            	title: {
                    text: '',
                },
                opposite: true,
                
                lineWidth: 1
            }],
            legend: {
                enabled: true,
                layout: "vertical"
            },
            credits: {
                enabled: false
            },
            tooltip: {
                valueSuffix: '',
                crosshairs: true,
                shared: true,
                useHTML: true,
                enabled: true
            },
            series: [{
                type: "line",
                name: "NMI",
                color: "#FF0000",
                pointInterval: 1,
                pointStart: 2,
                data: nmiArray,
                lineWidth: 1
            }]
        });

$('body').find('#overlappingmodularity').highcharts({
            chart: {
                zoomType: 'x'
            },
            title: {
                text: 'overlappingmodularity'
            },
            xAxis: {
                minTickInterval: 1,
                type: 'linear',
                title: {
                    text: 'Om',
                    legend: false
                }
            },
            yAxis: [{
                title: {
                    text: 'NMI',
                    legend: false
                },
                minTickInterval: 0.1,
                max: 1,
                min: 0,
                minRange: 1,
                lineWidth: 1
            },
            {
                title: {
                    text: '',
                },
                opposite: true,
                
                lineWidth: 1
            }],
            legend: {
                enabled: true,
                layout: "vertical"
            },
            credits: {
                enabled: false
            },
            tooltip: {
                valueSuffix: '',
                crosshairs: true,
                shared: true,
                useHTML: true,
                enabled: true
            },
            series: [{
                type: "line",
                name: "overlappingmodularity",
                color: "#FF0000",
                pointInterval: 1,
                pointStart: 2,
                data: nmiArray,
                lineWidth: 1
            }]
        });
plot(data, '#precision');
plot(data, '#recall');
plot(data, '#fscore');
plot(data, '#omega');
plot(data, '#nmi');
plot(data, '#overlappingmodularity');


